source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DCRadialGraph_Example', :exclusive => true do
  pod "DCRadialGraph", :path => "../"
end

target 'DCRadialGraph_Tests', :exclusive => true do
  pod "DCRadialGraph", :path => "../"

  
end
